var defaultMetroListVar = [
      {
         "cityName":"Hyderabad",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"HYDERABAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"AP-09 Hyderabad",

               "regisCode":"AP09",
               "state":"Andhra Pradesh",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"SECUNDERABAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"AP-10 Secunderabad",
               "regisCode":"AP10",
               "state":"Andhra Pradesh",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"MALAKPET HYDERABAD EAST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"AP-11 Malakpet Hyderabad East",
               "regisCode":"AP11",
               "state":"Andhra Pradesh",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"KISANBAGH HYDERABAD SOUTH",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"AP-12 Kisanbagh Hyderabad South",
               "regisCode":"AP12",
               "state":"Andhra Pradesh",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"TOLI CHOWKI HYDERABAD WEST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"AP-13 Toli Chowki Hyderabad West",
               "regisCode":"AP13",
               "state":"Andhra Pradesh",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"HYDERABAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TS-14 Hyderabad",
               "regisCode":"TS14",
               "state":"Telangana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"HYDERABAD CENTRAL",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TS-09 Hyderabad Central",
               "regisCode":"TS09",
               "state":"Telangana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"MALAKPET HYDERABAD EAST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TS-11 Malakpet Hyderabad East",
               "regisCode":"TS11",
               "state":"Telangana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"TOLI CHOWKI HYDERABAD WEST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TS-13 Toli Chowki Hyderabad West",
               "regisCode":"TS13",
               "state":"Telangana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Hyderabad"
            }
         ]
      },
      {
         "cityName":"Delhi",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"DELHI NORTH HILL ROAD",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-01 Delhi North Hill Road",
               "regisCode":"DL01",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"NEW DELHI",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-02 New Delhi",
               "regisCode":"DL02",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"SOUTH DELHI",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-03 South Delhi",
               "regisCode":"DL03",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"DELHI WEST RAJA GARDEN",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-04 Delhi West Raja Garden",
               "regisCode":"DL04",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"DELHI NORTH LONI ROAD",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-05 Delhi North Loni Road",
               "regisCode":"DL05",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"DELHI CENTRAL SARAI KALE KHAN",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"DL-06 Delhi Central Sarai Kale Khan",
               "regisCode":"DL06",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"DELHI EAST",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-07 Delhi East",
               "regisCode":"DL07",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"NORTH WEST DELHI",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-08 North West Delhi",
               "regisCode":"DL08",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"SOUTH WEST DELHI",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-09 South West Delhi",
               "regisCode":"DL09",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"WEST DELHI",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-10 West Delhi",
               "regisCode":"DL10",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"NORTH WEST DELHI",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-11 North West Delhi",
               "regisCode":"DL11",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"SOUTH WEST DELHI VASANT VIHAR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-12 South West Delhi Vasant Vihar",
               "regisCode":"DL12",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"EAST DELHI SHAHDARA",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-13 East Delhi Shahdara",
               "regisCode":"DL13",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"SONIPAT",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-14 Sonipat",
               "regisCode":"DL14",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Delhi"
            }
         ]
      },
      {
         "cityName":"Gurgaon",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"GURGAON",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-15 Gurgaon",
               "regisCode":"DL15",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Gurgaon"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"N",
               "crimeIndex":1,
               "city":"GURGAON",
               "trafficeIndex":1,
               "zone":"ZoneB",
               "display":"HR-26 Gurgaon",
               "regisCode":"HR26",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Gurgaon"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"GURGAON",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-55 Gurgaon",
               "regisCode":"HR55",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Gurgaon"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"GURGAON",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-72 Gurgaon",
               "regisCode":"HR72",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Gurgaon"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"PATAUDI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-76 Pataudi",
               "regisCode":"HR76",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Gurgaon"
            }
         ]
      },
      {
         "cityName":"Faridabad",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"FARIDABAD",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"DL-16 Faridabad",
               "regisCode":"DL16",
               "state":"Delhi",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Faridabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BALLABGARH",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-29 Ballabgarh",
               "regisCode":"HR29",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Faridabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"FARIDABAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-38 Faridabad",
               "regisCode":"HR38",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Faridabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"FARIDABAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"HR-51 Faridabad",
               "regisCode":"HR51",
               "state":"Haryana",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Faridabad"
            }
         ]
      },
      {
         "cityName":"Ahmedabad",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"AHMEDABAD",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"GJ-01 Ahmedabad",
               "regisCode":"GJ01",
               "state":"Gujarat",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Ahmedabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"AHMEDABAD EAST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"GJ-27 Ahmedabad East",
               "regisCode":"GJ27",
               "state":"Gujarat",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Ahmedabad"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"GIR SOMNATH VERAVAL",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"GJ-38 Gir Somnath Veraval",
               "regisCode":"GJ38",
               "state":"Gujarat",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Ahmedabad"
            }
         ]
      },
      {
         "cityName":"Bangalore",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"BANGALORE KORMANGALA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"KA-01 Bangalore Kormangala",
               "regisCode":"KA01",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"BANGALORE RAJAJINAGAR",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"KA-02 Bangalore Rajajinagar",
               "regisCode":"KA02",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"BANGALORE INDIRANAGAR",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"KA-03 Bangalore Indiranagar",
               "regisCode":"KA03",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"BANGALORE YASHWANTHPUR",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"KA-04 Bangalore Yashwanthpur",
               "regisCode":"KA04",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"BANGALORE JAYANAGAR",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"KA-05 Bangalore Jayanagar",
               "regisCode":"KA05",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BANGALORE KENGERI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-41 Bangalore Kengeri",
               "regisCode":"KA41",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"RAMANAGAR",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-42 Ramanagar",
               "regisCode":"KA42",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"DEVANAHALLI BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-43 Devanahalli Bangalore",
               "regisCode":"KA43",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BANGALORE YALAHANKA",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-50 Bangalore Yalahanka",
               "regisCode":"KA50",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BANGALORE ELECTRONIC CITY",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-51 Bangalore Electronic City",
               "regisCode":"KA51",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"NELAMANGALA BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-52 Nelamangala Bangalore",
               "regisCode":"KA52",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BANGALORE KRISHNARAJPURAM",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-53 Bangalore Krishnarajpuram",
               "regisCode":"KA53",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"SHANTINAGAR BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-57 Shantinagar Bangalore",
               "regisCode":"KA57",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHAMRAJPET BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-59 Chamrajpet Bangalore",
               "regisCode":"KA59",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"RT NAGAR BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-60 RT Nagar Bangalore",
               "regisCode":"KA60",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"MARATHAHALLI BANGALORE",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"KA-61 Marathahalli Bangalore",
               "regisCode":"KA61",
               "state":"Karnataka",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Bangalore"
            }
         ]
      },
      {
         "cityName":"Mumbai",
         "RTODetails":[
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"MUMBAI",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"MH-01 Mumbai Tardeo",
               "regisCode":"MH01",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"MUMBAI ANDHERI",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"MH-02 Mumbai Andheri",
               "regisCode":"MH02",
               "state":"Maharashtra",
               "isCostal":"Y",
               "pollutionIndex":1,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"MUMBAI WORLI",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"MH-03 Mumbai Worli",
               "regisCode":"MH03",
               "state":"Maharashtra",
               "isCostal":"Y",
               "pollutionIndex":1,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":1,
               "city":"THANE MUMBAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-04 Thane Mumbai",
               "regisCode":"MH04",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":1,
               "city":"KALYAN MUMBAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-05 Kalyan Mumbai",
               "regisCode":"MH05",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"NAVI MUMBAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-43 Navi Mumbai",
               "regisCode":"MH43",
               "state":"Maharashtra",
               "isCostal":"Y",
               "pollutionIndex":0,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BORIVALI MUMBAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-47 Borivali Mumbai",
               "regisCode":"MH47",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Mumbai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"VIRAR VASAI MUMBAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-48 Virar Vasai Mumbai",
               "regisCode":"MH48",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Mumbai"
            }
         ]
      },
      {
         "cityName":"Pune",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"PUNE",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"MH-12 Pune",
               "regisCode":"MH12",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Pune"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"PIMPRI CHINCHWAD",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-14 Pimpri Chinchwad",
               "regisCode":"MH14",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Pune"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"BARAMATI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-42 Baramati",
               "regisCode":"MH42",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Pune"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"PUNE SOUTH",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-53 Pune South",
               "regisCode":"MH53",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Pune"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"PUNE NORTH",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"MH-54 Pune North",
               "regisCode":"MH54",
               "state":"Maharashtra",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Pune"
            }
         ]
      },
      {
         "cityName":"Chennai",
         "RTODetails":[
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI TONDIARPET",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-03 Chennai Tondiarpet",
               "regisCode":"TN03",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI AYANAVARAM",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-01 Chennai Ayanavaram",
               "regisCode":"TN01",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI ANNANAGAR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-02 Chennai Annanagar",
               "regisCode":"TN02",
               "state":"Tamil Nadu",
               "isCostal":"Y",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI KOLATHUR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-04 Chennai Kolathur",
               "regisCode":"TN04",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI NORTH",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-05 Chennai North",
               "regisCode":"TN05",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI MANDAVELI",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-06 Chennai Mandaveli",
               "regisCode":"TN06",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI THIRUVANMIYUR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-07 Chennai Thiruvanmiyur",
               "regisCode":"TN07",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"Y",
               "crimeIndex":0,
               "city":"CHENNAI KK NAGAR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-09 Chennai KK Nagar",
               "regisCode":"TN09",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI VIRUGAMBAKKAM",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-10 Chennai Virugambakkam",
               "regisCode":"TN10",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI TAMBARAM",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-11 Chennai Tambaram",
               "regisCode":"TN11",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI POONAMALLEE",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-12 Chennai Poonamallee",
               "regisCode":"TN12",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI AMBATTUR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-13 Chennai Ambattur",
               "regisCode":"TN13",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI SHOLINGANALLUR",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-14 Chennai Sholinganallur",
               "regisCode":"TN14",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI RED HILLS",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"TN-18 Chennai Red Hills",
               "regisCode":"TN18",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"MEENAMBAKKAM CHENNAI",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TN-22 Meenambakkam Chennai",
               "regisCode":"TN22",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"CHENNAI SOUTH WEST",
               "trafficeIndex":0,
               "zone":"ZoneB",
               "display":"TN-85 Chennai South West",
               "regisCode":"TN85",
               "state":"Tamil Nadu",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Chennai"
            }
         ]
      },
      {
         "cityName":"Kolkata",
         "RTODetails":[
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-01 Kolkata",
               "regisCode":"WB01",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-02 Kolkata",
               "regisCode":"WB02",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA BELTALA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-03 Kolkata Beltala",
               "regisCode":"WB03",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA BELTALA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-04 Kolkata Beltala",
               "regisCode":"WB04",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA KASBA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-05 Kolkata Kasba",
               "regisCode":"WB05",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA KASBA",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-06 Kolkata Kasba",
               "regisCode":"WB06",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA SALT LAKE",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-07 Kolkata Salt Lake",
               "regisCode":"WB07",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":1,
               "isEarthQuakeArea":"Y",
               "crimeIndex":1,
               "city":"KOLKATA SALT LAKE",
               "trafficeIndex":1,
               "zone":"ZoneA",
               "display":"WB-08 Kolkata Salt Lake",
               "regisCode":"WB08",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":1,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"KOLKATA NEW TOWN",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"WB-09 Kolkata New Town",
               "regisCode":"WB09",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Kolkata"
            },
            {
               "floodIndex":0,
               "isEarthQuakeArea":"N",
               "crimeIndex":0,
               "city":"KOLKATA NEW TOWN",
               "trafficeIndex":0,
               "zone":"ZoneA",
               "display":"WB-10 Kolkata New Town",
               "regisCode":"WB10",
               "state":"West Bengal",
               "isCostal":"N",
               "pollutionIndex":0,
               "popularCityName":"Kolkata"
            }
         ]
      }
   ]